package main

import (
	"flag"
	"fmt"
	"io"
	"os"
	"sort"
	"strings"
)

// runCompletions implements `xdev completions <shell>` (issue #34). The script
// is generated from the root FlagSet the process actually parsed and from the
// subcommands map, so a new flag or subcommand is completed the moment it is
// registered — a hand-written list would drift the first time someone adds one.
func runCompletions(args []string, fs *flag.FlagSet) int {
	return completionsCmd(args, fs, os.Stdout, os.Stderr)
}

func completionsCmd(args []string, fs *flag.FlagSet, out, errOut io.Writer) int {
	shell := "bash"
	if len(args) > 0 {
		shell = strings.ToLower(strings.TrimSpace(args[0]))
	}
	if len(args) > 1 {
		fmt.Fprintln(errOut, "xdev completions: pass one shell (bash, zsh or fish)")
		return 2
	}
	switch shell {
	case "bash":
		fmt.Fprint(out, completionBash(fs))
	case "zsh":
		fmt.Fprint(out, completionZsh(fs))
	case "fish":
		fmt.Fprint(out, completionFish(fs))
	default:
		fmt.Fprintf(errOut, "xdev completions: unknown shell %q (want bash, zsh or fish)\n", shell)
		return 2
	}
	return 0
}

// completionNames is the sorted subcommand vocabulary: map iteration order is
// random, and completion candidates must be stable.
func completionNames() []string {
	names := make([]string, 0, len(subcommands))
	for name := range subcommands {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}

// completionFlag pairs a flag with the description the FlagSet carries.
type completionFlag struct {
	name  string
	usage string
}

// completionFlags reads the flags off the parsed root FlagSet (both the
// single- and double-dash spellings, since Go's flag package accepts both).
func completionFlags(fs *flag.FlagSet) []completionFlag {
	if fs == nil {
		return nil
	}
	var out []completionFlag
	fs.VisitAll(func(f *flag.Flag) {
		if f.Name == "h" || f.Name == "help" {
			return // provided by the shell itself
		}
		out = append(out, completionFlag{name: f.Name, usage: f.Usage})
	})
	sort.Slice(out, func(i, j int) bool { return out[i].name < out[j].name })
	return out
}

// completionDescriptions renders shell-safe descriptions: the usage strings
// carry brackets and backticks that would break a naive quoting.
func completionDescriptions(flags []completionFlag) string {
	var b strings.Builder
	for _, f := range flags {
		fmt.Fprintf(&b, "%s=%q\n", f.name, completionSanitize(f.usage))
	}
	return b.String()
}

// completionSanitize drops the characters that would end a quoted completion
// description early (both quoting styles are used below), and folds the
// brackets flags conventionally carry into parentheses.
func completionSanitize(usage string) string {
	replacer := strings.NewReplacer("[", "(", "]", ")", "`", "", "'", "", "\"", "", "\\", "", "$", "", "\n", " ")
	return replacer.Replace(usage)
}

func completionBash(fs *flag.FlagSet) string {
	flags := completionFlags(fs)
	words := make([]string, 0, len(flags)*2)
	for _, f := range flags {
		words = append(words, "-"+f.name, "--"+f.name)
	}
	var b strings.Builder
	b.WriteString("# xdev bash completion — generated by `xdev completions bash`\n")
	b.WriteString("_xdev() {\n")
	b.WriteString("    local cur subcommands flags\n")
	b.WriteString("    cur=\"${COMP_WORDS[COMP_CWORD]}\"\n")
	fmt.Fprintf(&b, "    subcommands=%q\n", strings.Join(completionNames(), " "))
	fmt.Fprintf(&b, "    flags=%q\n", strings.Join(words, " "))
	b.WriteString("    if [ \"$COMP_CWORD\" -eq 1 ]; then\n")
	b.WriteString("        COMPREPLY=( $(compgen -W \"$subcommands\" -- \"$cur\") )\n")
	b.WriteString("        return 0\n")
	b.WriteString("    fi\n")
	b.WriteString("    if [ \"${cur:0:1}\" = \"-\" ]; then\n")
	b.WriteString("        COMPREPLY=( $(compgen -W \"$flags\" -- \"$cur\") )\n")
	b.WriteString("        return 0\n")
	b.WriteString("    fi\n")
	b.WriteString("    COMPREPLY=( $(compgen -f -- \"$cur\") )\n")
	b.WriteString("    return 0\n")
	b.WriteString("}\n")
	b.WriteString("complete -o default -F _xdev xdev\n")
	return b.String()
}

func completionZsh(fs *flag.FlagSet) string {
	flags := completionFlags(fs)
	var b strings.Builder
	b.WriteString("#compdef xdev\n")
	b.WriteString("# xdev zsh completion — generated by `xdev completions zsh`\n")
	b.WriteString("_xdev() {\n")
	b.WriteString("    local -a subcommands\n")
	fmt.Fprintf(&b, "    subcommands=(%s)\n", strings.Join(completionNames(), " "))
	b.WriteString("    _arguments -s -S \\\n")
	b.WriteString("        '1:subcommand:->subcmd' \\\n")
	b.WriteString("        '*::argument:->args'\n")
	b.WriteString("    case \"$state\" in\n")
	b.WriteString("        subcmd) _describe -t commands 'xdev subcommand' subcommands ;;\n")
	b.WriteString("        args)\n")
	b.WriteString("            _arguments -s -S \\\n")
	for _, f := range flags {
		// Both spellings: the flag package accepts -flag and --flag. Every
		// line carries a continuation, and the fixed final row terminates
		// the command even when the FlagSet registers nothing.
		fmt.Fprintf(&b, "                '-%s[%s]' \\\n", f.name, completionSanitize(f.usage))
		fmt.Fprintf(&b, "                '--%s[%s]' \\\n", f.name, completionSanitize(f.usage))
	}
	b.WriteString("                '*:file:_files'\n")
	b.WriteString("            ;;\n")
	b.WriteString("    esac\n")
	b.WriteString("}\n")
	b.WriteString("_xdev \"$@\"\n")
	return b.String()
}

func completionFish(fs *flag.FlagSet) string {
	names := completionNames()
	var b strings.Builder
	b.WriteString("# xdev fish completion — generated by `xdev completions fish`\n")
	b.WriteString("function __xdev_needs_subcommand\n")
	b.WriteString("    for i in (commandline -opc)\n")
	b.WriteString("        if contains -- $i " + strings.Join(names, " ") + "\n")
	b.WriteString("            return 1\n")
	b.WriteString("        end\n")
	b.WriteString("    end\n")
	b.WriteString("    return 0\n")
	b.WriteString("end\n")
	b.WriteString("complete -c xdev -f\n")
	fmt.Fprintf(&b, "complete -c xdev -n '__xdev_needs_subcommand' -a '%s'\n", strings.Join(names, " "))
	for _, f := range completionFlags(fs) {
		// -l/--flag is the spelling people type; -o/--old-option covers the
		// single-dash form Go's flag package also accepts.
		fmt.Fprintf(&b, "complete -c xdev -o %s -l %s -d '%s'\n", f.name, f.name, completionSanitize(f.usage))
	}
	return b.String()
}
